Repository kahikatea-2019/kidskash, pull requests merged in 2019-05, with the labels that each got.

#71 45 get route for users db
  knexfile.js
  package-lock.json
  package.json
  routes/parents.js
  server/db/parents.js
  tests/routes/parents.test.js
  tests/server/db/parents.test.js
  tests/server/db/seeds/parents.js
  tests/test-environment.js
Labels: Routes

#90 76 get route child table
  README.md
  package-lock.json
  routes/children.js
  server/db/children.js
  tests/routes/children.test.js
  tests/server/db/children.test.js
  tests/server/db/seeds/children.js
Labels: DB, Routes, Test

#93 82 boilerplate reduxify
  client/actions/actions.js
  client/actions/children.js
  client/api.js
  client/components/App.jsx
  client/index.js
  client/reducers/index.js
  client/reducers/retrieveAllChildren.js
  routes/children.js
  server/db/children.js
  server/server.js
Labels: redux

#102 Creating child login component 6
  client/components/ChildLogin.jsx
  package-lock.json
  server/public/images/babyA.jpg
  server/public/images/babyB.jpg
  server/public/images/babyD.jpg
  server/public/images/babyE.jpg
  server/public/images/babyP.jpg
  tests/components/childLogin.test.js
Labels: react

#123 110 star bank action
  client/actions/starbanks.js
  client/components/App.jsx
  client/reducers/index.js
  client/reducers/retrieveAllStarBanks.js
  routes/children.js
  routes/starbanks.js
  server/db/migrations/20190511174352_starbank.js
  server/db/migrations/20190511174352_starbanks.js
  server/db/seeds/starbank.js
  server/db/starbanks.js
  server/server.js
Labels: redux

#127 125 post route wishes
  client/actions/wishes.js
  client/components/WishInput.jsx
  client/components/WishList.jsx
  client/index.js
  client/reducers/input.js
  client/reducers/navigate.js
  client/reducers/retrieveAllWishes.js
  routes/wishes.js
  server/db/migrations/20190509224636_wishes.js
  server/db/seeds/wishes.js
  server/db/wishes.js
Labels: DB, redux

#154 Fixed test
  package-lock.json
  package.json
  server/db/seeds/starbank.js
  tests/client/reducers/retrieveAllWishes.test.js
  tests/client/reducers/retrieveAllchildren.test.js
  tests/components/__snapshots__/childDashboard.test.js.snap
  tests/components/app.test.js
  tests/components/childDashboard.test.js
  tests/components/childLogin.test.js
  tests/components/wishlist.test.js
  tests/server/db/children.test.js
  tests/server/db/seeds/children.js
  tests/server/db/seeds/starbank.js
  tests/server/db/seeds/wishes.js
  tests/server/db/starbanks.test.js
  tests/server/db/wishes.test.js
Labels: Test
